<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyName>Goober.WebJobs</AssemblyName>
		<RootNamespace>Goober.WebJobs</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>6.0.0.7</Version>
		<Authors>Goober</Authors>
		<PackageId>Goober.WebJobs</PackageId>
		<Product>Goober.WebJobs</Product>
		<PackageReleaseNotes>Создана SimpleJob. Добавлен флаг запуска webjob на старте.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Polly" Version="7.2.3" />
		<PackageReference Include="System.Threading.Tasks.Dataflow" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Goober.Web.Abstractions\Goober.Web.Abstractions.csproj" />
	  <ProjectReference Include="..\Goober.WebJobs.Api\Goober.WebJobs.Api.csproj" />
	</ItemGroup>

</Project>
