<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Authors>Goober</Authors>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>6.0.0.2</Version>
		<PackageReleaseNotes>Создана SimpleJob. Добавлен флаг запуска webjob на старте.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Goober.Standard\Goober.DependencyInjection\Goober.DependencyInjection.csproj" />
	  <ProjectReference Include="..\..\Goober.Standard\Goober.Http.Abstractions\Goober.Http.Abstractions.csproj" />
	  <ProjectReference Include="..\Goober.Web.Abstractions\Goober.Web.Abstractions.csproj" />
	</ItemGroup>

</Project>
