<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>6.0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Goober.Standard\Goober.Base\Goober.Base.csproj" />
    <ProjectReference Include="..\..\Goober.Web.Authorization\Goober.Web.Authorization.csproj" />
  </ItemGroup>

</Project>
