<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Version>6.0.0.1</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>WebApi.Example.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Goober.Standard\Goober.DependencyInjection\Goober.DependencyInjection.csproj" />
    <ProjectReference Include="..\Goober.WebApi.Example.Api\Goober.WebApi.Example.Api.csproj" />
    <ProjectReference Include="..\Goober.Web\Goober.Web.csproj" />
  </ItemGroup>

</Project>
